### ISSUE TITLE
Location field in objects in folder Benutzergruppen takes no change

### ISSUE THREAD

**Issue by acsr** [collective/plonesite.de#17]
I edited http://www.plone.de/mitmachen/gruppen/pycologne-python-usergroup-koeln/edit
from RZUG to PyCologne

and could save successfully except that changes of the field for location (the one related to the map) was not changeable via browser edit.

I am not sure if this depends on permissions or whatever. Needs some investigation...

**Comment by Gomez** [comment]
Wir haben die Maps und locations bei der Migration zu Plone 5.2 entfernt.
