### ISSUE TITLE
Link zum Tracker im Footer autorisieren und im Product einbauen

### ISSUE THREAD

**Issue by acsr** [collective/plonesite.de#18]
Habe eben im Footer einen Link zum Tracker "vorläufig" als Action im ZMI eingebaut. Wollte ich erst nur intern machen, habe ich aber öffentlich gemacht, da jeder den ohne viel suchen nutzen können sollte.

Bei Zustimmung in den Code übernehmen.

Es reicht dann, einfach in einer Mail, im Chat oder im Gespräch den Link im Footer zu erwähnen oder sich dort zu holen. Der Link zeigt derzeit direkt auf den Issue Tracker

Noch bessere Alternative: Link zunächst auf eine Landing Page auf Plone.de zeigen lassen, die erklärt was man machen soll wenn man Ideen hat und / oder einen Zugang möchte.

Zusätzlich wäre auch ein redirect ala http://plone.de/tracker sinnvoll, egal wo die Seite dann liegt.

Jetzt erzählt mir nicht, dass man das nicht braucht. Je leichter es ist ohne rumsuchen einen Vorschlag professionell als Ticket einzureichen, umso eher wird es gemacht und umgesetzt.

**Comment by Gomez** [comment]
Den tracker gibt es nicht mehr.
