### ISSUE TITLE
Portal Tab Benutzergruppen not valid anymore

### ISSUE THREAD

**Issue by acsr** [collective/plonesite.de#8]
Tab is hardcoded link in portal_actions/portal_tabs .

Solution: Fix in content (already created a link object) and/or portal actions. 

Dependend issues: 
- Setting of type "link" -> "Follow links at once" is not active anymore! So anonymous users need to click twice.
- Poasible target is linked from landig page "/mitmachen/" pointing to "/mitmachen/gruppen". Target folder exists but default page is broken and not fixable with my permissions. Folder contains not working content (chat) etc.

ToDo: Create tickets for link integrity tests on site and fix content experience BEFORE WPD.

**Comment by Gomez** [comment]
Alt und nicht mehr relevant -> Closing
